/* MEGA BANCO DE PREGUNTAS ICFES (Simulación de Extracción Web 2020-2025) */
/* Este archivo contiene un nuevo lote de preguntas enfocadas en las competencias más evaluadas */
/* para que el sistema tenga un repertorio mucho más amplio. */

INSERT INTO public.questions_bank (subject_id, category, question_text, options, correct_index, explanation, difficulty, year)
VALUES
/* Lectura Crítica (subject_id: 1) */
(1, 'interpretacion', 'Según el artículo de divulgación científica sobre la edición genética (CRISPR), el autor advierte que:', '["La ciencia perderá su financiamiento.", "Se podrían crear desigualdades si solo los ricos acceden a mejoras genéticas.", "Los virus mutarán más rápido que nuestras curas.", "La clonación humana será obligatoria."]', 1, 'El texto advierte sobre las implicaciones éticas y socioeconómicas de la tecnología, específicamente la brecha de desigualdad.', 'high', 2024),
(1, 'literal', 'En la novela "Cien años de soledad", ¿qué evento marca el inicio de la decadencia de Macondo?', '["El asesinato de José Arcadio Buendía.", "La fiebre del insomnio.", "La llegada de la compañía bananera.", "El diluvio que duró casi cinco años."]', 3, 'El diluvio es el punto de quiebre que arruina a Macondo y marca el inicio de su desaparición final.', 'medium', 2023),
(1, 'filosofia', 'El mito de la caverna de Platón se utiliza principalmente para explicar:', '["La necesidad de vivir en la naturaleza.", "Cómo los sentidos nos engañan y la importancia de buscar el conocimiento verdadero (las ideas).", "La arquitectura de las prisiones griegas.", "Por qué la oscuridad es preferible a la luz."]', 1, 'Platón usa el mito para ilustrar el paso de la ignorancia (sombras) al conocimiento verdadero (la luz del sol).', 'medium', 2022),
(1, 'interpretacion', 'En una caricatura política donde un político corta la rama de un árbol sobre la que él mismo está sentado, el mensaje central es:', '["El daño ambiental causado por la deforestación.", "La ironía de tomar decisiones que terminarán perjudicando al propio tomador de decisiones.", "La importancia de la industria maderera.", "El peligro del trabajo físico no supervisado."]', 1, 'Es una metáfora visual clásica sobre la autodestrucción o las consecuencias imprevistas de malas decisiones.', 'medium', 2025),
(1, 'literal', 'De acuerdo con el texto sobre la Revolución Industrial, el principal cambio demográfico fue:', '["La migración masiva del campo a las ciudades (urbanización).", "El aumento de la población rural.", "La emigración hacia otros continentes exclusivamente.", "La disminución de la tasa de natalidad."]', 0, 'La creación de fábricas atrajo a los campesinos hacia los centros urbanos.', 'easy', 2021),

/* Matemáticas (subject_id: 2) */
(2, 'algebra', 'En una prueba ICFES, el puntaje P se calcula como P = 3x - 2y, donde x son las respuestas correctas e y las incorrectas. Si un estudiante respondió 50 preguntas y obtuvo 110 puntos, ¿cuántas respondió correctamente?', '["38", "40", "42", "45"]', 2, 'Sistema: x + y = 50 -> y = 50 - x. Sustituyendo: 3x - 2(50 - x) = 110 -> 5x - 100 = 110 -> 5x = 210 -> x = 42.', 'high', 2024),
(2, 'geometria', 'Un cilindro tiene un volumen de 100π cm³. Si su altura es de 4 cm, ¿cuál es su radio?', '["5 cm", "10 cm", "25 cm", "50 cm"]', 0, 'V = π * r² * h. 100π = π * r² * 4. r² = 25, por lo tanto r = 5.', 'medium', 2025),
(2, 'estadistica', 'En un salón de clases, el promedio de notas de 10 estudiantes es 4.0. Si un estudiante adicional se une y el nuevo promedio es 4.1, ¿cuál fue la nota del estudiante adicional?', '["4.1", "4.5", "5.0", "5.1"]', 3, 'Suma inicial = 10 * 4.0 = 40. Nueva suma = 11 * 4.1 = 45.1. Nota del estudiante = 45.1 - 40 = 5.1.', 'high', 2023),
(2, 'calculo', '¿Cuál es el valor máximo de la función f(x) = -2x² + 8x - 3?', '["2", "3", "5", "8"]', 2, 'El vértice está en x = -b/(2a) = -8 / (2*-2) = 2. Evaluando f(2) = -2(4) + 8(2) - 3 = -8 + 16 - 3 = 5.', 'high', 2022),
(2, 'estadistica', 'Si se escoge un número al azar del 1 al 100, ¿cuál es la probabilidad de que sea múltiplo de 3 o de 5?', '["47%", "53%", "60%", "33%"]', 0, 'Múltiplos de 3: 33. Múltiplos de 5: 20. Múltiplos de 15 (intersección): 6. Probabilidad = (33 + 20 - 6) / 100 = 47%.', 'high', 2021),

/* Sociales (subject_id: 3) */
(3, 'historia', 'Durante el siglo XX, América Latina experimentó múltiples dictaduras militares bajo el contexto de la Guerra Fría. Muchas de estas fueron apoyadas por Estados Unidos a través de:', '["El Plan Marshall.", "La Operación Cóndor y la Doctrina de Seguridad Nacional.", "La Alianza del Pacífico.", "El Pacto de Varsovia."]', 1, 'La Operación Cóndor fue un plan coordinado de represión en el Cono Sur con respaldo estadounidense.', 'medium', 2025),
(3, 'economia', 'Cuando el Banco de la República en Colombia decide aumentar la tasa de interés de intervención, su principal objetivo macroeconómico suele ser:', '["Fomentar el consumo masivo.", "Aumentar el empleo rápidamente.", "Controlar la inflación encareciendo el crédito.", "Incrementar las importaciones."]', 2, 'Subir tasas encarece los préstamos, reduciendo el dinero circulante y enfriando la inflación.', 'high', 2024),
(3, 'geografia', 'El desplazamiento forzado en Colombia históricamente se ha concentrado en zonas que cumplen con cierta característica. ¿Cuál es?', '["Zonas con climas gélidos.", "Corredores estratégicos para el narcotráfico y extracción de recursos.", "Grandes centros metropolitanos.", "Islas del Caribe colombiano."]', 1, 'Los actores armados disputan territorios ricos en recursos o útiles para el tráfico ilícito.', 'medium', 2023),
(3, 'constitucion', 'Un ciudadano considera que un artículo de una ley recién aprobada viola un derecho consagrado en la Constitución. El mecanismo idóneo para demandar esta norma es:', '["Acción de Tutela.", "Acción Popular.", "Acción Pública de Inconstitucionalidad.", "Derecho de Petición."]', 2, 'Cualquier ciudadano puede demandar una ley ante la Corte Constitucional mediante esta acción.', 'high', 2022),
(3, 'historia', 'El "Bogotazo" no solo destruyó el centro de la capital, sino que a nivel nacional causó:', '["La inmediata separación de Panamá.", "El inicio oficial del Frente Nacional.", "Una recrudescencia extrema de la violencia bipartidista rural.", "La redacción de la Constitución de 1991."]', 2, 'El asesinato de Gaitán en 1948 exacerbó drásticamente el conflicto entre liberales y conservadores en los campos.', 'medium', 2021),

/* Ciencias (subject_id: 4) */
(4, 'biologia', 'El dogma central de la biología molecular establece que el flujo de información genética ocurre en el siguiente orden:', '["ARN -> ADN -> Proteína", "ADN -> Proteína -> ARN", "ADN -> ARN -> Proteína", "Proteína -> ARN -> ADN"]', 2, 'La transcripción pasa la información del ADN al ARN, y la traducción del ARN a la proteína.', 'medium', 2025),
(4, 'quimica', 'Si un gas ideal duplica su temperatura absoluta (Kelvin) manteniendo la presión constante, de acuerdo con la Ley de Charles, su volumen:', '["Se reduce a la mitad.", "Se duplica.", "Se mantiene constante.", "Aumenta exponencialmente."]', 1, 'V1/T1 = V2/T2. Si T se duplica, V también debe duplicarse para mantener la igualdad.', 'medium', 2024),
(4, 'fisica', 'Un bloque se desliza sobre una superficie horizontal con fricción. Si se duplica la masa del bloque, la fuerza de fricción cinética:', '["No cambia.", "Se reduce a la mitad.", "Se duplica.", "Se cuadruplica."]', 2, 'La fuerza de fricción es f = μ*N. En una superficie horizontal, N = m*g. Si m se duplica, N y por ende la fricción, se duplican.', 'high', 2023),
(4, 'biologia', '¿Qué proceso ecológico explica cómo una zona rocosa estéril se convierte lentamente en un bosque a lo largo de los siglos?', '["Sucesión ecológica primaria.", "Sucesión ecológica secundaria.", "Radiación adaptativa.", "Evolución convergente."]', 0, 'La sucesión primaria comienza en hábitats donde no había suelo previo (ej: roca desnuda tras lava).', 'high', 2022),
(4, 'quimica', 'En una reacción exotérmica, la energía de los productos es:', '["Mayor que la de los reactivos.", "Menor que la de los reactivos.", "Igual a la de los reactivos.", "Cero."]', 1, 'Al liberar energía al entorno en forma de calor (exotérmica), los productos quedan con menor energía potencial que los reactivos.', 'medium', 2021),

/* Ingles (subject_id: 5) */
(5, 'vocabulary', 'Choose the best word to complete the sentence: "Despite the heavy rain, the football match was not ________."', '["put on", "called off", "brought up", "taken over"]', 1, '"Called off" means cancelled.', 'medium', 2025),
(5, 'grammar', 'Which sentence is grammatically correct?', '["She asked me where did I live.", "She asked me where I lived.", "She asked me where do I live.", "She asked me where lived I."]', 1, 'In indirect speech (embedded questions), we do not use the auxiliary "do/did" and the word order is subject + verb.', 'high', 2024),
(5, 'reading', 'Text: "The new software update aims to mitigate security flaws." What does "mitigate" mean?', '["To completely destroy.", "To increase the severity.", "To make less severe or harmful.", "To ignore intentionally."]', 2, 'Mitigate means to alleviate or lessen the impact of something negative.', 'high', 2023),
(5, 'grammar', 'If I ________ you, I would study more for the ICFES exam.', '["was", "were", "am", "have been"]', 1, 'In the second conditional, "were" is used for all subjects to express a hypothetical situation (subjunctive mood).', 'medium', 2022),
(5, 'vocabulary', 'The word "flawless" is closest in meaning to:', '["Defective", "Perfect", "Broken", "Average"]', 1, '"Flawless" means without any flaws or defects, therefore, perfect.', 'easy', 2021);
