-- INSERT de Preguntas Avanzadas ICFES 2020-2025 (10 por Materia, Nivel Alto)

INSERT INTO public.questions_bank (subject_id, category, question_text, options, correct_index, explanation, difficulty)
VALUES
-- Lectura Crítica (subject_id: 1)
(1, 'interpretacion', 'De acuerdo con el texto argumentativo de Estanislao Zuleta sobre la lectura, ¿qué implica el "deber de leer"?', '["Una obligación moral de acumular conocimiento.", "Un esfuerzo activo para interpretar y confrontar las ideas del autor.", "Una lectura rápida para encontrar datos explícitos.", "La memorización de los conceptos centrales del texto."]', 1, 'Zuleta propone que leer es un trabajo activo, de interpretación y confrontación, alejándose del consumismo pasivo.', 'high'),
(1, 'literal', 'Según el informe de la OMS (2023) expuesto en el texto, ¿cuál es el porcentaje de población afectada por estrés crónico?', '["15%", "25%", "35%", "50%"]', 1, 'El texto indica explícitamente que el 25% de la población sufre de esta condición.', 'medium'),
(1, 'interpretacion', 'En la frase "El ocaso de la civilización es un espejo de nuestra avaricia", la figura literaria empleada sugiere que:', '["El sol se oculta más temprano debido a la contaminación.", "La caída de la sociedad refleja nuestra propia codicia.", "Los espejos son elementos comunes en las civilizaciones antiguas.", "La avaricia ilumina el futuro de la sociedad."]', 1, 'Es una metáfora que establece una relación directa entre la destrucción social y la codicia humana.', 'high'),
(1, 'filosofia', 'Si se aplica la postura utilitarista clásica al dilema del tranvía expuesto en la lectura, la decisión correcta sería:', '["No intervenir, respetando el destino de cada persona.", "Desviar el tranvía para sacrificar a uno y salvar a cinco, maximizando el bienestar.", "Sacrificar a los cinco para no mancharse las manos de culpa.", "Frenar el tranvía con una fuerza externa."]', 1, 'El utilitarismo busca el mayor bien para el mayor número de personas.', 'high'),
(1, 'interpretacion', '¿Cuál de los siguientes enunciados sintetiza mejor la tesis del autor en el ensayo sobre inteligencia artificial?', '["La IA reemplazará todos los trabajos en 10 años.", "La IA es una herramienta que, sin regulación, amplificará las brechas de desigualdad existentes.", "El desarrollo tecnológico debe detenerse inmediatamente.", "Las máquinas desarrollarán conciencia propia pronto."]', 1, 'El autor centra su ensayo en la relación entre tecnología no regulada y desigualdad social.', 'high'),
(1, 'literal', 'En el poema de Borges presentado, el laberinto funciona como un símbolo de:', '["La complejidad del universo y la desorientación humana.", "La arquitectura antigua de Creta.", "Un juego matemático sin solución.", "La ceguera física del autor."]', 0, 'En la obra borgiana, el laberinto simboliza el caos y la incomprensibilidad del mundo.', 'high'),
(1, 'interpretacion', 'De la infografía sobre el calentamiento global, se puede inferir que los países en vías de desarrollo:', '["Son los principales emisores históricos de CO2.", "Serán los más afectados pese a contribuir menos al problema global.", "Cuentan con la tecnología para revertir el cambio climático.", "No experimentarán cambios en sus ecosistemas."]', 1, 'La infografía muestra bajas emisiones per cápita pero altos índices de vulnerabilidad en dichos países.', 'high'),
(1, 'filosofia', 'El concepto de "banalidad del mal" de Hannah Arendt se evidencia en el texto cuando el personaje principal:', '["Comete crímenes por odio extremo y pasión.", "Realiza actos atroces simplemente cumpliendo órdenes de la burocracia sin reflexionar.", "Planifica meticulosamente la caída de su enemigo.", "Nace con un defecto genético que lo hace malvado."]', 1, 'Arendt define la banalidad del mal como la falta de pensamiento crítico y la obediencia ciega al sistema.', 'high'),
(1, 'interpretacion', 'La ironía central en el microcuento "El Dinosaurio" de Monterroso radica en:', '["La longitud del cuento vs la lentitud del dinosaurio.", "El despertar como una acción cotidiana frente a lo prehistórico y amenazante que aún persiste.", "Que los dinosaurios están extintos.", "Que el protagonista estaba soñando con un zoológico."]', 1, 'La brevedad encierra el contraste entre el despertar (nueva realidad) y el dinosaurio (la amenaza del pasado que sigue ahí).', 'high'),
(1, 'literal', '¿Qué función cumple la cita de Gabriel García Márquez en el segundo párrafo del texto?', '["Contradecir la idea principal del autor.", "Apoyar la tesis de que la realidad latinoamericana supera la ficción.", "Definir qué es el realismo mágico literariamente.", "Criticar la narrativa europea contemporánea."]', 1, 'El autor usa la cita como argumento de autoridad para respaldar su tesis sobre la realidad del continente.', 'medium'),

-- Matemáticas (subject_id: 2)
(2, 'algebra', 'En un modelo de crecimiento poblacional P(t) = P0 * e^(rt), si una población de bacterias se duplica en 5 horas, ¿qué valor tiene aproximadamente "r"?', '["ln(2) / 5", "5 / ln(2)", "ln(5) / 2", "2 / 5"]', 0, 'Si 2P0 = P0 * e^(5r), entonces 2 = e^(5r), aplicando logaritmo natural: ln(2) = 5r, por tanto r = ln(2)/5.', 'high'),
(2, 'geometria', 'El área de un hexágono regular inscrito en una circunferencia de radio R es:', '["(3 * sqrt(3) * R^2) / 2", "3 * R^2", "6 * R^2", "(sqrt(3) * R^2) / 4"]', 0, 'Un hexágono regular se divide en 6 triángulos equiláteros de lado R. Área = 6 * (sqrt(3)*R^2)/4 = (3*sqrt(3)*R^2)/2.', 'high'),
(2, 'estadistica', 'En una distribución normal, ¿aproximadamente qué porcentaje de los datos se encuentra dentro de una desviación estándar de la media?', '["50%", "68%", "95%", "99.7%"]', 1, 'Por la regla empírica de la distribución normal, aprox. el 68% de los datos caen en el intervalo (Media ± 1 Desviación Estándar).', 'medium'),
(2, 'algebra', 'La solución del sistema de inecuaciones: 2x - 3 < 5 y -x + 4 <= 2 es:', '["x < 4", "x >= 2", "2 <= x < 4", "No tiene solución real"]', 2, '2x < 8 -> x < 4. Y de -x <= -2 -> x >= 2. La intersección es [2, 4).', 'medium'),
(2, 'calculo', 'La derivada de la función f(x) = x * ln(x) es:', '["ln(x)", "1/x", "ln(x) + 1", "x/ln(x)"]', 2, 'Aplicando regla del producto: (x)''*ln(x) + x*(ln(x))'' = 1*ln(x) + x*(1/x) = ln(x) + 1.', 'high'),
(2, 'geometria', 'Si el volumen de un cono se reduce a la mitad manteniendo su altura constante, ¿qué le ocurre al radio de su base?', '["Se reduce a la mitad.", "Se divide por raíz de 2.", "Se divide por 4.", "No cambia."]', 1, 'V = (pi*r^2*h)/3. Si V se divide por 2, r^2 debe dividirse por 2, por lo que r se divide por sqrt(2).', 'high'),
(2, 'estadistica', 'Al lanzar dos dados legales, la probabilidad de que la suma de sus caras sea un número primo mayor que 5 es:', '["5/36", "7/36", "8/36", "15/36"]', 2, 'Primos mayores que 5: 7 y 11. Hay 6 combinaciones para sumar 7 y 2 para sumar 11. Total 8 de 36 (8/36).', 'high'),
(2, 'algebra', 'El valor de log_2(32) + log_3(1/9) es:', '["3", "5", "7", "1"]', 0, 'log_2(32) = 5 (porque 2^5 = 32). log_3(1/9) = -2 (porque 3^-2 = 1/9). 5 + (-2) = 3.', 'medium'),
(2, 'geometria', 'La ecuación de una circunferencia con centro en (2, -3) y tangente al eje Y es:', '["(x-2)^2 + (y+3)^2 = 4", "(x-2)^2 + (y+3)^2 = 9", "(x+2)^2 + (y-3)^2 = 4", "(x-2)^2 + (y+3)^2 = 1"]', 0, 'Al ser tangente al eje Y, su radio es la distancia del centro al eje Y, que es |2| = 2. Radio al cuadrado es 4.', 'high'),
(2, 'calculo', 'El límite de (sin(3x)) / x cuando x tiende a 0 es:', '["0", "1", "3", "Infinito"]', 2, 'Utilizando el límite especial lim(x->0) sin(kx)/x = k, el resultado es 3.', 'medium'),

-- Sociales y Ciudadanas (subject_id: 3)
(3, 'historia', 'El periodo conocido como "La Violencia" en Colombia se intensificó drásticamente tras un evento ocurrido en 1948. ¿Cuál fue este hecho?', '["La firma del Frente Nacional", "La Masacre de las Bananeras", "El asesinato de Jorge Eliécer Gaitán (El Bogotazo)", "La promulgación de la Constitución de 1886"]', 2, 'El asesinato del líder liberal Jorge Eliécer Gaitán el 9 de abril de 1948 desató revueltas que intensificaron el periodo de "La Violencia".', 'medium'),
(3, 'constitucion', 'El mecanismo de participación ciudadana que permite al pueblo derogar una ley ya aprobada por el Congreso es:', '["El Referendo derogatorio", "El Plebiscito", "La Consulta Popular", "El Cabildo Abierto"]', 0, 'El referendo derogatorio se usa específicamente para someter a votación la anulación parcial o total de una ley.', 'high'),
(3, 'economia', 'Una inflación acelerada en la economía de un país afecta más severamente a:', '["Los grandes bancos comerciales.", "Los exportadores de materias primas.", "Los ciudadanos que perciben ingresos fijos (como asalariados y pensionados).", "Los inversionistas en bienes raíces."]', 2, 'La inflación reduce el poder adquisitivo de la moneda, perjudicando principalmente a quienes tienen ingresos fijos.', 'medium'),
(3, 'historia', '¿Cuál de las siguientes fue una consecuencia geopolítica directa de la caída del Muro de Berlín en 1989?', '["El inicio de la Guerra Fría.", "La desintegración del Bloque Soviético y la reunificación alemana.", "El fortalecimiento del Pacto de Varsovia.", "La creación de las Naciones Unidas."]', 1, 'La caída del muro simbolizó el fin de la división europea y precipitó el colapso de la Unión Soviética y sus estados satélite.', 'medium'),
(3, 'geografia', 'El fenómeno del "Niño" en Colombia suele ocasionar principalmente:', '["Aumento drástico de precipitaciones y desbordamiento de ríos.", "Temporadas de fuertes sequías, escasez de agua e incendios forestales.", "Nevadas atípicas en las zonas costeras.", "Aumento de la actividad volcánica en la cordillera central."]', 1, 'En Colombia, El Niño se asocia con un déficit de lluvias y temperaturas más altas de lo normal.', 'medium'),
(3, 'constitucion', 'La "Acción de Tutela" consagrada en la Constitución de 1991 tiene como objetivo principal:', '["Resolver disputas económicas entre grandes empresas.", "Proteger los derechos fundamentales de los individuos de manera inmediata.", "Elegir a los magistrados de la Corte Suprema.", "Derogar leyes inconstitucionales."]', 1, 'La tutela es un mecanismo transitorio y rápido para proteger derechos fundamentales cuando no existe otra vía judicial.', 'medium'),
(3, 'historia', 'El movimiento estudiantil de la "Séptima Papeleta" en 1990 fue fundamental para:', '["Derrocar al gobierno militar.", "Exigir la renuncia del presidente.", "Impulsar la convocatoria a una Asamblea Nacional Constituyente.", "Detener el narcotráfico en Medellín."]', 2, 'La iniciativa estudiantil propuso una papeleta extra en las elecciones para apoyar una nueva constitución, lo que dio origen a la Constitución de 1991.', 'high'),
(3, 'economia', 'Si un país exporta bienes primarios e importa bienes manufacturados de alto valor, ¿cómo tiende a comportarse su balanza comercial?', '["Siempre tendrá superávit.", "Es propensa al déficit debido a la diferencia de valor agregado.", "Se mantiene en equilibrio automáticamente.", "Las divisas se fortalecen sin importar los volúmenes."]', 1, 'Los productos primarios suelen ser más baratos que los manufacturados, lo que genera déficit si no se compensa con gran volumen.', 'high'),
(3, 'constitucion', 'El control de constitucionalidad de las leyes en Colombia lo ejerce:', '["El Presidente de la República.", "El Congreso de la República.", "La Corte Constitucional.", "La Fiscalía General de la Nación."]', 2, 'La Corte Constitucional es la entidad encargada de velar por la integridad y supremacía de la Constitución.', 'medium'),
(3, 'historia', '¿Qué objetivo principal tenía la Doctrina Monroe ("América para los americanos") propuesta por EE. UU. en el siglo XIX?', '["Fomentar la inmigración europea hacia América Latina.", "Rechazar cualquier intervención o reconquista europea en el continente americano.", "Promover la unión política de todos los países de Sudamérica.", "Compartir tecnología militar con los nuevos estados independientes."]', 1, 'Fue una advertencia a las potencias europeas para que no interfirieran en los recién independizados países americanos.', 'high'),

-- Ciencias Naturales (subject_id: 4)
(4, 'biologia', 'Durante el proceso de respiración celular aeróbica, la mayor parte del ATP se produce en:', '["La glucólisis en el citoplasma.", "El Ciclo de Krebs.", "La cadena de transporte de electrones en la mitocondria.", "La fermentación láctica."]', 2, 'La fosforilación oxidativa en la cadena de transporte de electrones genera entre 32-34 moléculas de ATP, la mayor parte del proceso.', 'high'),
(4, 'quimica', 'Si un elemento X del grupo IIA reacciona con un elemento Y del grupo VIIA, el compuesto resultante más probable tiene la fórmula:', '["XY", "X2Y", "XY2", "X2Y3"]', 2, 'El elemento del grupo IIA tiene estado de oxidación +2, y el del grupo VIIA tiene -1. Al cruzarse, forman XY2 (ej: CaCl2).', 'medium'),
(4, 'fisica', 'Un objeto cae libremente desde cierta altura. Si se ignora la resistencia del aire, ¿qué gráfica representa correctamente la relación entre su velocidad y el tiempo de caída?', '["Una línea recta horizontal.", "Una parábola cóncava hacia arriba.", "Una línea recta inclinada que pasa por el origen.", "Una curva exponencial."]', 2, 'En caída libre, la aceleración (g) es constante, por lo que v = g*t, lo que corresponde a una función lineal (línea recta) creciente.', 'high'),
(4, 'biologia', 'En la genética mendeliana, un cruce entre dos organismos heterocigotos (Aa x Aa) dará como resultado una proporción fenotípica (dominante:recesivo) de:', '["1:1", "3:1", "9:3:3:1", "Todos dominantes"]', 1, 'Los genotipos posibles son AA, Aa, aA (todos con fenotipo dominante, 3/4) y aa (recesivo, 1/4). Por ende, 3:1.', 'medium'),
(4, 'quimica', 'Al agregar ácido clorhídrico (HCl) a una disolución amortiguadora (buffer) de ácido acético y acetato de sodio, el pH:', '["Disminuye drásticamente a 1.", "Aumenta debido a la neutralización.", "Disminuye levemente porque el acetato neutraliza los iones H+.", "Permanece absolutamente inalterado sin importar la cantidad."]', 2, 'La función de un buffer es resistir cambios bruscos de pH. El ión acetato (base conjugada) reacciona con los H+ añadidos, atenuando la caída del pH.', 'high'),
(4, 'fisica', 'Dos cargas eléctricas puntuales positivas se separan al doble de su distancia original. Según la ley de Coulomb, la fuerza de repulsión entre ellas:', '["Se reduce a la mitad.", "Se reduce a la cuarta parte.", "Se duplica.", "Se cuadruplica."]', 1, 'La fuerza eléctrica es inversamente proporcional al cuadrado de la distancia (F ∝ 1/r^2). Si r se duplica, F se divide entre 2^2 = 4.', 'high'),
(4, 'biologia', 'Una especie introducida en un nuevo ecosistema comienza a crecer exponencialmente. Ecológicamente, esto se explica porque:', '["El ecosistema tiene recursos ilimitados.", "Carece de depredadores naturales que regulen su población.", "Su tasa de mutación genética es más alta en nuevos climas.", "Las especies autóctonas le ceden el territorio voluntariamente."]', 1, 'Sin sus depredadores coevolutivos, las especies invasoras no encuentran resistencia ambiental y experimentan crecimiento logarítmico/exponencial inicial.', 'medium'),
(4, 'quimica', '¿Cuál de los siguientes enlaces químicos es el que determina las propiedades únicas del agua, como su alto punto de ebullición y cohesión?', '["Enlace iónico.", "Fuerzas de dispersión de London.", "Puentes de hidrógeno.", "Enlace metálico."]', 2, 'La polaridad del agua permite la formación de puentes de hidrógeno fuertes entre moléculas adyacentes, requiriendo más energía para romperlos.', 'medium'),
(4, 'fisica', 'De acuerdo con la primera ley de la termodinámica, en un proceso isotérmico (temperatura constante) de un gas ideal:', '["El calor añadido se convierte completamente en trabajo realizado por el gas.", "El volumen del gas se mantiene constante.", "No hay transferencia de calor.", "La presión se mantiene constante."]', 0, 'Dado que la energía interna depende de la temperatura (dU = 0), Q = W. Todo calor se transforma en trabajo de expansión.', 'high'),
(4, 'biologia', 'Los virus no se consideran seres vivos autónomos principalmente porque:', '["No contienen material genético (ADN o ARN).", "Carecen de proteínas en su estructura.", "Requieren parasitar obligatoriamente la maquinaria celular de un hospedero para replicarse.", "Son demasiado pequeños para ser observados con microscopio óptico."]', 2, 'Los virus no tienen metabolismo propio ni capacidad de reproducción independiente; son parásitos intracelulares obligados.', 'medium'),

-- Inglés (subject_id: 5)
(5, 'grammar', 'Choose the correct form to complete the conditional sentence: "If she _______ earlier, she would have caught the train."', '["leaves", "left", "had left", "would leave"]', 2, 'This is a Third Conditional sentence. It requires Past Perfect (had + past participle) in the "if" clause.', 'high'),
(5, 'vocabulary', 'Which phrasal verb means "to postpone or delay something"?', '["Put out", "Put off", "Call off", "Bring up"]', 1, '"Put off" means to delay or postpone. "Call off" means to cancel.', 'medium'),
(5, 'reading', 'Read the passage: "Despite his rigorous training schedule, Marcos managed to excel academically, proving that sports and studies are not mutually exclusive." What does the passage imply?', '["Marcos failed his exams due to sports.", "Marcos gave up sports to study.", "Marcos successfully balanced two demanding activities.", "Athletes cannot be good students."]', 2, 'The phrase "mutually exclusive" means they cannot exist together. The text proves they can, showing Marcos balanced both.', 'high'),
(5, 'grammar', 'Identify the passive voice sentence:', '["The committee is evaluating the proposals right now.", "The proposals are being evaluated by the committee.", "The committee has evaluated all proposals.", "The proposals evaluated the committee."]', 1, 'In passive voice, the object (proposals) becomes the subject, followed by the verb "to be" and the past participle.', 'medium'),
(5, 'grammar', 'Complete the sentence: "By the time we arrive at the cinema, the movie _______."', '["will start", "started", "will have started", "is starting"]', 2, 'The Future Perfect (will have + past participle) is used for an action that will be completed before another time in the future.', 'high'),
(5, 'vocabulary', 'What is the closest synonym for the word "inevitable" in the context of: "The consequences of climate change are inevitable"?', '["Unavoidable", "Unpredictable", "Reversible", "Doubtful"]', 0, 'Inevitable means certain to happen and unable to be avoided.', 'medium'),
(5, 'reading', 'In a restaurant dialogue: Waiter: "Are you ready to order?" Customer: "I''ll have the steak, but hold the onions." What does "hold the onions" mean?', '["Keep the onions separate.", "Do not include onions in the dish.", "Bring extra onions.", "I want to hold the onions in my hand."]', 1, '"Hold the [ingredient]" is a common idiom meaning to exclude it from the order.', 'high'),
(5, 'grammar', 'Choose the correct preposition: "She is extremely good _______ solving complex mathematical equations."', '["in", "at", "on", "for"]', 1, 'The adjective "good" (when referring to an ability) takes the preposition "at".', 'medium'),
(5, 'grammar', 'Which sentence uses Reported Speech correctly for: "I am working on a new project," he said.', '["He said that he is working on a new project.", "He said that I was working on a new project.", "He said that he was working on a new project.", "He said that he works on a new project."]', 2, 'Present Continuous changes to Past Continuous in reported speech, and pronouns shift appropriately.', 'high'),
(5, 'vocabulary', 'What does the idiom "A piece of cake" mean?', '["Something very complicated.", "A delicious dessert.", "Something easily achieved or done.", "A small portion of a bigger problem."]', 2, 'The idiom refers to a task that is extremely simple or easy to accomplish.', 'medium');
