export const EXAM_QUESTIONS = {
  1: [ // Lectura Crítica - Nivel Avanzado ICFES
    { q: '[ICFES 2023] En una columna periodística, el autor argumenta: "La automatización destruirá millones de empleos, pero creará otros nuevos que requieren habilidades tecnológicas. Sin embargo, el Estado debe intervenir para evitar una crisis social transitoria". ¿Cuál es la premisa principal subyacente al argumento?', options: ['La tecnología siempre es negativa para la sociedad.', 'El progreso tecnológico requiere una red de seguridad estatal durante la transición.', 'Los empleos tecnológicos son más fáciles que los manuales.', 'El Estado debe prohibir el avance de la automatización.'], correct: 1, explanation: 'La premisa central es que, aunque el cambio es inevitable, se requiere intervención del Estado para mitigar el impacto social inmediato.', category: 'interpretacion' },
    { q: '[ICFES 2024] Lee el siguiente fragmento: "La luna, testigo mudo de mil batallas, se ocultó tras un velo de nubes grises, como si no quisiera presenciar la masacre". La figura retórica predominante y su propósito en el texto es:', options: ['Símil, para comparar la luna con las nubes.', 'Hipérbole, para exagerar el número de batallas.', 'Personificación, para dotar de sensibilidad al entorno natural frente a la tragedia humana.', 'Metáfora, para explicar la astronomía.'], correct: 2, explanation: 'Al atribuirle la voluntad de "no querer presenciar" o ser un "testigo mudo", se está humanizando la luna (personificación) para intensificar el dramatismo.', category: 'interpretacion' },
    { q: '[ICFES 2022] Un texto expositivo sobre historia económica señala que "la inflación descontrolada erosiona el poder adquisitivo, golpeando desproporcionadamente a los estratos bajos". A partir de esto, se puede deducir que:', options: ['La inflación beneficia a los más pobres.', 'Los estratos altos son inmunes a cualquier problema económico.', 'La pérdida de valor del dinero afecta más severamente a quienes tienen ingresos fijos y limitados.', 'La economía no depende de la inflación.'], correct: 2, explanation: 'Se infiere que los estratos bajos sufren más porque no tienen activos para protegerse de la pérdida del valor del dinero.', category: 'interpretacion' },
    { q: '[ICFES 2025] Si un político afirma: "Mi oponente propone aumentar los impuestos porque odia a los empresarios y quiere destruir el empleo", está incurriendo en una falacia de tipo:', options: ['Ad hominem (ataque personal).', 'Hombre de paja (tergiversar la postura del oponente).', 'Falso dilema.', 'Apelación a la autoridad.'], correct: 1, explanation: 'Asignar intenciones extremas y falsas ("odia a los empresarios") a la propuesta del oponente para atacarla fácilmente es la falacia del hombre de paja.', category: 'general' },
    { q: '[ICFES 2021] En el poema de Borges, el laberinto simboliza frecuentemente:', options: ['Un juego de niños.', 'La estructura geométrica perfecta de la ciudad.', 'La complejidad inabarcable y confusa del universo y el destino humano.', 'El miedo irracional a perderse.'], correct: 2, explanation: 'El laberinto en la literatura borgiana representa la perplejidad del hombre frente a un mundo que no puede descifrar por completo.', category: 'interpretacion' }
  ],
  2: [ // Matemáticas - Nivel Avanzado ICFES
    { q: '[ICFES 2024] En un colegio, la probabilidad de que un estudiante juegue fútbol es 0.6. De los que juegan fútbol, el 30% también juega baloncesto. ¿Cuál es la probabilidad de que un estudiante elegido al azar juegue AMBOS deportes?', options: ['0.18', '0.9', '0.3', '0.5'], correct: 0, explanation: 'Se multiplican las probabilidades: 0.6 (fútbol) * 0.3 (baloncesto dado fútbol) = 0.18 (18%).', category: 'interpretacion' },
    { q: '[ICFES 2023] Se desea construir un cilindro con un volumen fijo de 1000 cm³. Para minimizar el costo del material (minimizar el área superficial), el radio "r" y la altura "h" deben cumplir cierta relación. Sin usar cálculo diferencial, las proporciones ideales en optimización geométrica de cilindros sugieren que:', options: ['La altura debe ser el doble del diámetro.', 'El diámetro de la base debe ser igual a la altura.', 'El radio debe ser igual a la altura.', 'La altura debe ser nula.'], correct: 1, explanation: 'En optimización, el área mínima para un volumen dado en un cilindro se logra cuando su diámetro (2r) es exactamente igual a su altura (h).', category: 'general' },
    { q: '[ICFES 2025] En un estudio demográfico, se modela el crecimiento de una bacteria con la ecuación P(t) = 500 * (2)^(t/3), donde t está en horas. ¿Cuántas horas deben pasar para que la población sea de 4000 bacterias?', options: ['3 horas', '6 horas', '9 horas', '12 horas'], correct: 2, explanation: '4000 = 500 * 2^(t/3) -> 8 = 2^(t/3) -> 2^3 = 2^(t/3) -> 3 = t/3 -> t = 9 horas.', category: 'literal' },
    { q: '[ICFES 2022] Un gráfico de dispersión muestra una correlación de r = -0.92 entre "Horas de uso de redes sociales" y "Calificaciones escolares". Esto indica matemáticamente que:', options: ['El uso de redes sociales causa directamente malas notas.', 'No hay ninguna relación entre las variables.', 'Existe una fuerte asociación estadística inversa: a más horas de redes, tienden a bajar las calificaciones.', 'Las notas son negativas.'], correct: 2, explanation: 'Un coeficiente cercano a -1 indica una fuerte correlación negativa, pero no prueba causalidad directa obligatoria, solo tendencia estadística.', category: 'interpretacion' },
    { q: '[ICFES 2021] Si sen(θ) = 3/5 y θ está en el primer cuadrante, el valor exacto de cos(θ) es:', options: ['4/5', '5/3', '2/5', '1'], correct: 0, explanation: 'Por identidad pitagórica: sen² + cos² = 1. (3/5)² = 9/25. 1 - 9/25 = 16/25. La raíz es 4/5.', category: 'literal' }
  ],
  3: [ // Sociales y Ciudadanas - Nivel Avanzado ICFES
    { q: '[ICFES 2024] En un municipio, el Alcalde decide construir una represa que inundará tierras de comunidades indígenas protegidas. La Constitución de 1991 exige que, antes de iniciar la obra, el Estado debe obligatoriamente:', options: ['Pagarles el doble del valor de las tierras.', 'Realizar una Consulta Previa libre e informada con las comunidades afectadas.', 'Ignorar a la comunidad por el bien general del país.', 'Hacer un plebiscito nacional.'], correct: 1, explanation: 'La Consulta Previa es un derecho constitucional fundamental de grupos étnicos para proteger su integridad cultural y territorial.', category: 'general' },
    { q: '[ICFES 2023] ¿Cuál fue una de las causas estructurales económicas que motivó el surgimiento de las guerrillas de corte marxista en Colombia durante la década de 1960?', options: ['La influencia exclusiva de la Iglesia Católica.', 'La reforma agraria exitosa que eliminó la desigualdad.', 'La aguda concentración de la propiedad de la tierra y la exclusión política tras el Frente Nacional.', 'El descubrimiento de grandes yacimientos de oro en Antioquia.'], correct: 2, explanation: 'El problema agrario (latifundismo) y el cierre político (Frente Nacional) fueron caldos de cultivo para los alzamientos armados.', category: 'interpretacion' },
    { q: '[ICFES 2025] Al presentarse un conflicto entre el derecho al libre desarrollo de la personalidad (ej. llevar el cabello largo) y el manual de convivencia de un colegio, la Corte Constitucional colombiana suele fallar que:', options: ['El colegio siempre tiene la razón absoluta.', 'El derecho constitucional prima sobre normas disciplinarias internas si no se afecta el núcleo educativo.', 'El estudiante debe ser expulsado inmediatamente.', 'El manual de convivencia es superior a la Constitución.'], correct: 1, explanation: 'La jurisprudencia protege el libre desarrollo de la personalidad, indicando que el cabello no afecta el proceso de aprendizaje.', category: 'interpretacion' },
    { q: '[ICFES 2022] La Revolución Francesa y la Independencia de los Estados Unidos influyeron en la emancipación latinoamericana porque:', options: ['Enviaron tropas y armas masivamente.', 'Implantaron dictaduras en América.', 'Proporcionaron el marco ideológico de soberanía popular, derechos humanos y república.', 'Prohibieron la esclavitud mundial.'], correct: 2, explanation: 'El legado ideológico de la Ilustración inspiró los procesos independentistas criollos.', category: 'general' },
    { q: '[ICFES 2021] ¿Qué mecanismo constitucional se debe usar para demandar la nulidad de una ley que contradice los principios de la Constitución?', options: ['Acción de Tutela.', 'Acción Popular.', 'Acción Pública de Inconstitucionalidad.', 'Derecho de Petición.'], correct: 2, explanation: 'La Acción de Inconstitucionalidad permite a cualquier ciudadano demandar leyes ante la Corte Constitucional.', category: 'general' }
  ],
  4: [ // Ciencias Naturales - Nivel Avanzado ICFES
    { q: '[ICFES 2024] En una reacción química endotérmica en equilibrio, A + B + Calor ⇌ C + D. Según el Principio de Le Chatelier, si se incrementa la temperatura del sistema:', options: ['El equilibrio se desplaza hacia la izquierda (reactivos).', 'El equilibrio se desplaza hacia la derecha, favoreciendo la formación de productos (C + D).', 'El sistema colapsa y se congela.', 'No hay ningún efecto en el equilibrio.'], correct: 1, explanation: 'Al aumentar la temperatura, el sistema busca absorber ese calor adicional desplazándose hacia la reacción endotérmica (hacia los productos).', category: 'interpretacion' },
    { q: '[ICFES 2023] Desde el punto de vista genético y evolutivo, el uso excesivo e incorrecto de antibióticos en la medicina genera:', options: ['Pacientes que desarrollan inmunidad al medicamento.', 'Superbacterias, debido a que las bacterias resistentes sobreviven y heredan esa resistencia por selección natural.', 'Virus más fuertes que atacan el hígado.', 'Mutaciones instantáneas inducidas por el antibiótico en todas las células.'], correct: 1, explanation: 'Es un ejemplo clásico de selección natural: el antibiótico elimina las débiles, y las que tienen resistencia genética previa sobreviven y se multiplican.', category: 'interpretacion' },
    { q: '[ICFES 2025] Un bloque de 10 kg se desliza hacia abajo por un plano inclinado rugoso a velocidad constante. De esto podemos afirmar sobre las fuerzas físicas que:', options: ['La fuerza neta que actúa sobre el bloque es cero porque no hay aceleración.', 'La fuerza de fricción es nula.', 'La gravedad ya no ejerce efecto sobre el bloque.', 'La fuerza normal es mayor que el peso total.'], correct: 0, explanation: 'Según la 1ª Ley de Newton, si la velocidad es constante, la aceleración es 0, por ende, la sumatoria de fuerzas (neta) es cero.', category: 'literal' },
    { q: '[ICFES 2022] En ecología de poblaciones, si se introduce una especie invasora sin depredadores naturales en un ecosistema frágil, la gráfica de crecimiento poblacional de esta especie en sus primeros años será:', options: ['Lineal descendente.', 'Exponencial (curva en J), debido a la ausencia de resistencia ambiental inmediata.', 'Constante.', 'Logística instantánea.'], correct: 1, explanation: 'Sin factores limitantes, el crecimiento inicial se dispara exponencialmente agotando los recursos.', category: 'interpretacion' },
    { q: '[ICFES 2021] ¿Cuál es la función primaria de los ribosomas en el citoplasma celular eucariota?', options: ['Generar energía en forma de ATP.', 'Destruir patógenos.', 'Sintetizar proteínas a partir de la información del ARN mensajero.', 'Almacenar agua y nutrientes.'], correct: 2, explanation: 'Los ribosomas son las "fábricas" donde ocurre la traducción del ARN en cadenas polipeptídicas (proteínas).', category: 'general' }
  ],
  5: [ // Inglés - Nivel Avanzado ICFES
    { q: '[ICFES 2025] Pragmatics: Where would you most likely see a sign that reads: "UNATTENDED LUGGAGE WILL BE DESTROYED BY SECURITY"?', options: ['In a public library.', 'At an international airport terminal.', 'In a kindergarten.', 'At a local grocery store.'], correct: 1, explanation: 'Luggage (equipaje) and security destruction due to bomb threats is typical of airport environments.', category: 'interpretacion' },
    { q: '[ICFES 2024] Complete the mixed conditional sentence: "If I had studied harder for the final exams last year, I ___ at the university right now."', options: ['will be', 'would have been', 'would be', 'was'], correct: 2, explanation: 'Mixed conditional: Past unreal condition (had studied) with a present unreal result (would be).', category: 'general' },
    { q: '[ICFES 2023] Reading comprehension: "Despite the prevailing economic downturn, the startup managed to secure unprecedented venture capital funding". What does "unprecedented" mean in this context?', options: ['Terrible and low.', 'Average and expected.', 'Never done or known before; exceptionally high.', 'Illegal.'], correct: 2, explanation: '"Unprecedented" means without a precedent, something entirely new or extraordinary.', category: 'interpretacion' },
    { q: '[ICFES 2022] Which sentence is grammatically correct in the Passive Voice?', options: ['The novel was writing by Gabriel García Márquez.', 'The novel was written by Gabriel García Márquez.', 'The novel wrote Gabriel García Márquez.', 'Gabriel García Márquez is written the novel.'], correct: 1, explanation: 'Passive voice structure requires: Subject + to be (was) + Past Participle (written).', category: 'literal' },
    { q: '[ICFES 2021] Pragmatic implication: If a teacher says "It\'s getting quite noisy in here, isn\'t it?", she is most likely:', options: ['Asking a genuine question about acoustics.', 'Requesting the students to be quiet politely.', 'Complimenting the students on their energy.', 'Going to play loud music.'], correct: 1, explanation: 'This is an indirect speech act common in English to politely command silence.', category: 'interpretacion' }
  ]
};

// Banco de preguntas para las pruebas de práctica (10 preguntas aleatorias o dinámicas por examen)
export const PRACTICE_QUESTIONS = {
  1: {
    literal: [
      { q: '[ICFES 2024] En el texto "El estado gasta el 30% del presupuesto en educación", la información literal principal es:', options: ['El estado invierte en salud.', 'La educación no sirve.', 'Un 30% del dinero estatal se destina a educación.', 'Los profesores ganan poco.'], correct: 2, explanation: 'Es una paráfrasis literal.' }
    ],
    interpretacion: [
      { q: '[ICFES 2023] Si el autor termina su ensayo diciendo "Nos encaminamos hacia un precipicio digital con los ojos vendados", su postura frente a las redes es de:', options: ['Optimismo absoluto.', 'Indiferencia total.', 'Grave preocupación y alerta por la ignorancia de los usuarios.', 'Apoyo incondicional.'], correct: 2, explanation: '"Precipicio" y "ojos vendados" denotan peligro inminente e inconsciencia.' },
      { q: '[ICFES 2025] "El rumor corrió como pólvora". Esta figura indica:', options: ['Lentitud.', 'Velocidad y capacidad expansiva.', 'Que hubo un incendio literal.', 'Que el rumor era falso.'], correct: 1, explanation: 'Símil de propagación rápida.' }
    ],
    general: [
      { q: '[ICFES 2022] Un texto que presenta premisas para llegar a una conclusión con el fin de persuadir al lector se denomina:', options: ['Descriptivo.', 'Argumentativo.', 'Lírico.', 'Informativo.'], correct: 1, explanation: 'La persuasión y justificación lógica son bases del texto argumentativo.' }
    ]
  },
  2: {
    literal: [
      { q: '[ICFES 2024] La ecuación de una parábola básica con vértice en el origen y que abre hacia arriba es:', options: ['y = x', 'y = x^3', 'y = x^2', 'y = -x^2'], correct: 2, explanation: 'Una cuadrática positiva (y = x^2) dibuja una parábola cóncava hacia arriba.' }
    ],
    interpretacion: [
      { q: '[ICFES 2025] Si al lanzar dos dados normales se quiere obtener una suma de 7, ¿cuántas combinaciones favorables existen?', options: ['3', '6', '12', '1'], correct: 1, explanation: 'Combinaciones: (1,6), (2,5), (3,4), (4,3), (5,2), (6,1). Son 6 opciones.' },
      { q: '[ICFES 2023] En un triángulo rectángulo, si los catetos miden 3 cm y 4 cm, la hipotenusa mide:', options: ['5 cm', '7 cm', '1 cm', '25 cm'], correct: 0, explanation: 'Teorema de Pitágoras: h = raíz(3^2 + 4^2) = raíz(9+16) = raíz(25) = 5.' }
    ],
    general: [
      { q: '[ICFES 2021] En la estadística descriptiva, el valor que representa el dato central cuando todos están ordenados de menor a mayor es:', options: ['La media.', 'La moda.', 'La mediana.', 'La varianza.'], correct: 2, explanation: 'Definición estricta de mediana.' }
    ]
  },
  3: {
    literal: [
      { q: '[ICFES 2024] El acuerdo de Paz entre el Gobierno colombiano y las FARC-EP se firmó definitivamente en el año:', options: ['2012', '1991', '2016', '2020'], correct: 2, explanation: 'El Acuerdo del Teatro Colón se firmó en noviembre de 2016.' }
    ],
    interpretacion: [
      { q: '[ICFES 2025] El aumento acelerado del precio del dólar en un país latinoamericano usualmente genera:', options: ['Abundancia de importaciones baratas.', 'Aumento en el costo de los productos importados (inflación importada).', 'Que nadie viaje al extranjero jamás.', 'Deflación económica instantánea.'], correct: 1, explanation: 'Si la moneda local se devalúa, comprar del exterior cuesta más dinero.' },
      { q: '[ICFES 2023] Históricamente, el sistema económico feudal europeo se basaba principalmente en:', options: ['La bolsa de valores.', 'La industria petrolera.', 'La propiedad de la tierra (feudos) y la relación vasallo-señor.', 'El libre mercado global.'], correct: 2, explanation: 'Tierra y servidumbre eran la base medieval.' }
    ],
    general: [
      { q: '[ICFES 2022] La rama del poder público en Colombia encargada de ejecutar las políticas públicas y administrar el Estado es:', options: ['Legislativa.', 'Ejecutiva.', 'Judicial.', 'Electoral.'], correct: 1, explanation: 'Encabezada por el Presidente.' }
    ]
  },
  4: {
    literal: [
      { q: '[ICFES 2024] La fórmula química del dióxido de carbono es:', options: ['CO', 'CO2', 'C2O', 'H2O'], correct: 1, explanation: 'Un carbono y dos oxígenos.' }
    ],
    interpretacion: [
      { q: '[ICFES 2025] Si conectas 3 bombillas en serie y una se funde (se quema), ¿qué ocurre con las demás?', options: ['Brillan más fuerte.', 'Siguen igual.', 'Todas se apagan porque el circuito se interrumpe.', 'Explotan.'], correct: 2, explanation: 'En serie, la corriente tiene un solo camino. Si se corta, no hay flujo.' },
      { q: '[ICFES 2023] ¿Por qué los glóbulos rojos no pueden realizar mitosis?', options: ['Porque son muy rápidos.', 'Porque maduran y pierden su núcleo celular, perdiendo su ADN.', 'Porque son bacterias.', 'Porque no tienen mitocondrias.'], correct: 1, explanation: 'Los eritrocitos mamíferos carecen de núcleo para almacenar más oxígeno.' }
    ],
    general: [
      { q: '[ICFES 2022] La Ley de Conservación de la Masa fue postulada por:', options: ['Isaac Newton.', 'Albert Einstein.', 'Antoine Lavoisier.', 'Charles Darwin.'], correct: 2, explanation: 'Lavoisier postuló que la materia no se crea ni se destruye.' }
    ]
  },
  5: {
    literal: [
      { q: '[ICFES 2024] Vocabulary: Choose the correct translation for "Medio ambiente".', options: ['Weather.', 'Environment.', 'Surroundings.', 'Ecosystem.'], correct: 1, explanation: '"Environment" es el término exacto para Medio ambiente.' }
    ],
    interpretacion: [
      { q: '[ICFES 2025] Reading: "She was completely over the moon when she saw her exam results". This implies she was:', options: ['Studying astronomy.', 'Very sad.', 'Extremely happy and delighted.', 'Sleeping.'], correct: 2, explanation: 'Idiom: "Over the moon" significa estar inmensamente feliz.' },
      { q: '[ICFES 2023] Pragmatics: If a waiter asks "Would you like some room for dessert?", what does "room" mean?', options: ['Una habitación de hotel.', 'Espacio en el estómago para el postre.', 'Dinero.', 'Silla.'], correct: 1, explanation: 'Room se usa figurativamente para "capacidad/espacio".' }
    ],
    general: [
      { q: '[ICFES 2022] Grammar: "I ___ to London three times in my life." What goes in the blank?', options: ['have been', 'went', 'go', 'was going'], correct: 0, explanation: 'Present Perfect para experiencias de vida no atadas a un tiempo pasado específico.' }
    ]
  }
};
