-- Banco de Preguntas Masivo para SinPanic0 - Simulación ICFES 2024-2025
-- Copia y pega todo este código en el editor SQL de Supabase para añadir las preguntas.

INSERT INTO questions_bank (subject_id, category, difficulty, question_text, options, correct_index, explanation, year)
VALUES 
-- LECTURA CRÍTICA (subject_id = 1)
(1, 'interpretacion', 'high', 'Lee el siguiente microcuento: "Cuando despertó, el dinosaurio todavía estaba allí." (Monterroso). La interpretación más profunda sugiere que:', '["El narrador estaba soñando con el pasado.", "El cuento habla sobre la prehistoria.", "El dinosaurio representa un problema, un temor o un estado opresivo ineludible que sobrevive al paso del tiempo.", "Es una descripción biológica."]'::jsonb, 2, 'La brevedad permite múltiples interpretaciones, siendo la más aceptada que el dinosaurio simboliza algo persistente e inamovible.', 2024),
(1, 'literal', 'medium', 'Según el texto: "La Revolución Industrial trajo consigo la urbanización masiva y la creación de la clase obrera". ¿Cuál fue una consecuencia directa mencionada?', '["La creación de la agricultura.", "La urbanización masiva.", "La caída del imperio romano.", "El descubrimiento de América."]'::jsonb, 1, 'Es una pregunta de nivel literal. Se extrae textualmente la información de la premisa.', 2024),
(1, 'general', 'high', 'Un artículo científico concluye que "el calentamiento global es una realidad innegable; no obstante, algunos sectores empresariales financian estudios para minimizar su impacto mediático". La intención del autor es:', '["Apoyar a los sectores empresariales.", "Informar neutralmente sobre el clima.", "Denunciar la manipulación de la información por intereses económicos.", "Negar el calentamiento global."]'::jsonb, 2, 'El uso del conector "no obstante" y el verbo "minimizar" evidencian una postura crítica hacia la financiación de desinformación.', 2025),
(1, 'interpretacion', 'high', 'El refrán "En casa de herrero, azadón de palo" da a entender que:', '["Los herreros son pobres.", "Falta algo en un lugar donde debería sobrar o ser habitual.", "La madera es mejor que el hierro.", "Los herreros usan herramientas de madera."]'::jsonb, 1, 'Es una paradoja donde la profesión no se aplica en el hogar.', 2023),
(1, 'general', 'medium', 'En la oración: "A pesar de la fuerte lluvia, el evento se realizó con normalidad", ¿qué función cumple la frase inicial?', '["Conector de adición.", "Conector de causalidad.", "Conector concesivo, indica un obstáculo que no impide la acción.", "Conector temporal."]'::jsonb, 2, '"A pesar de" indica concesión: una dificultad que no evita el resultado final.', 2024),
(1, 'literal', 'low', 'En el texto "La fotosíntesis es el proceso mediante el cual las plantas producen su propio alimento", se define la fotosíntesis como:', '["Un proceso animal.", "La forma en que las plantas se reproducen.", "El proceso por el que las plantas producen su alimento.", "Una teoría extinta."]'::jsonb, 2, 'La información está explícita en la oración principal.', 2025),
(1, 'interpretacion', 'high', 'Si el autor afirma "Estamos caminando dormidos hacia el borde de un acantilado ecológico", su tono es:', '["Optimista y relajado.", "Indiferente y científico.", "Alarmista y crítico sobre nuestra inacción frente al clima.", "Humorístico."]'::jsonb, 2, 'La metáfora "caminando dormidos hacia un acantilado" refleja un gran peligro inminente ignorado por la humanidad.', 2024),
(1, 'general', 'high', 'El principal propósito de un ensayo argumentativo es:', '["Narrar una historia entretenida.", "Describir un paisaje en detalle.", "Convencer al lector de una postura mediante razones lógicas y evidencias.", "Explicar las instrucciones para usar un aparato."]'::jsonb, 2, 'La función comunicativa de la argumentación es la persuasión y justificación lógica.', 2025),

-- MATEMÁTICAS (subject_id = 2)
(2, 'general', 'high', 'Un cultivo de bacterias se duplica cada 4 horas. Si inicialmente hay 100 bacterias, ¿cuántas habrá después de 12 horas?', '["400", "800", "1200", "600"]'::jsonb, 1, 'A las 4h: 200. A las 8h: 400. A las 12h: 800. O mediante fórmula: 100 * 2^(12/4) = 100 * 2^3 = 800.', 2024),
(2, 'interpretacion', 'medium', 'En una gráfica de pastel, si una porción representa el 25% del total, ¿cuál es el ángulo de dicho sector circular?', '["45°", "90°", "120°", "180°"]'::jsonb, 1, 'El círculo completo tiene 360°. El 25% de 360 es 90°.', 2025),
(2, 'literal', 'low', '¿Cuál es el valor de x en la ecuación 3x - 5 = 16?', '["4", "5", "7", "21"]'::jsonb, 2, '3x = 16 + 5 -> 3x = 21 -> x = 7.', 2023),
(2, 'general', 'high', 'Si la probabilidad de que llueva el sábado es 0.4 y la probabilidad de que llueva el domingo es 0.3, y ambos eventos son independientes, ¿cuál es la probabilidad de que llueva AMBOS días?', '["0.12", "0.7", "0.1", "0.012"]'::jsonb, 0, 'Eventos independientes se multiplican: 0.4 * 0.3 = 0.12.', 2024),
(2, 'interpretacion', 'high', 'El área de un círculo A se cuadruplica. ¿Qué ocurrió con su radio?', '["Se duplicó.", "Se cuadruplicó.", "Se redujo a la mitad.", "Aumentó en 4 unidades."]'::jsonb, 0, 'El área es π*r^2. Para que el área se multiplique por 4, el radio debe multiplicarse por 2, ya que 2^2 = 4.', 2025),
(2, 'literal', 'medium', 'Un artículo cuesta $200 y tiene un descuento del 15%. ¿Cuál es el precio final?', '["185", "170", "150", "215"]'::jsonb, 1, '15% de 200 es 30. 200 - 30 = 170.', 2024),
(2, 'general', 'high', 'En un triángulo rectángulo, si los catetos miden 6 cm y 8 cm, ¿cuánto mide la hipotenusa?', '["10 cm", "14 cm", "12 cm", "100 cm"]'::jsonb, 0, 'Por teorema de Pitágoras: h^2 = 6^2 + 8^2 = 36 + 64 = 100. h = 10.', 2025),
(2, 'interpretacion', 'medium', 'La función f(x) = -2x^2 + 4x + 1 representa una parábola que:', '["Abre hacia arriba y tiene un punto mínimo.", "Abre hacia abajo y tiene un punto máximo.", "Es una línea recta ascendente.", "Es una línea recta descendente."]'::jsonb, 1, 'Al ser el coeficiente de x^2 negativo (-2), la parábola es cóncava hacia abajo, por lo tanto tiene un máximo absoluto.', 2023),

-- SOCIALES Y CIUDADANAS (subject_id = 3)
(3, 'general', 'medium', 'El mecanismo de participación ciudadana mediante el cual se le pregunta al pueblo sobre una decisión de trascendencia nacional, departamental o local es:', '["Acción de Tutela.", "Plebiscito.", "Consulta Popular.", "Cabildo Abierto."]'::jsonb, 2, 'La Consulta Popular es la pregunta formal al pueblo sobre un asunto de trascendencia para que se pronuncie.', 2024),
(3, 'interpretacion', 'high', 'Una de las consecuencias de la Guerra Fría en América Latina fue:', '["El apoyo a dictaduras militares bajo la Doctrina de Seguridad Nacional para frenar el comunismo.", "La completa desmilitarización del continente.", "El cierre de fronteras con Europa.", "El fin de la pobreza extrema."]'::jsonb, 0, 'EE.UU. apoyó dictaduras de derecha en la región para evitar la expansión de la influencia soviética y cubana.', 2025),
(3, 'literal', 'medium', '¿Cuál de los siguientes es considerado un mecanismo de protección de derechos humanos fundamentales en Colombia?', '["Habeas Corpus.", "Acción de Tutela.", "Ambas opciones A y B.", "La demanda civil."]'::jsonb, 2, 'Tanto el Habeas Corpus (libertad física) como la Acción de Tutela protegen derechos fundamentales.', 2024),
(3, 'general', 'high', 'El fenómeno de la globalización económica se caracteriza principalmente por:', '["El cierre de las economías nacionales para proteger la industria local.", "La libre circulación de mercancías, capitales e información a nivel mundial.", "El control estatal absoluto de los medios de producción.", "La prohibición de tratados de libre comercio."]'::jsonb, 1, 'La globalización busca la interdependencia económica mundial reduciendo barreras comerciales.', 2025),
(3, 'interpretacion', 'high', 'La segregación socioespacial en ciudades latinoamericanas ocurre cuando:', '["Diferentes clases sociales conviven en el mismo barrio.", "La población es distribuida geográficamente según su nivel de ingresos, concentrando la riqueza y marginando la pobreza.", "Las ciudades construyen más parques.", "Todos usan transporte público."]'::jsonb, 1, 'Es la separación física en el espacio urbano basada en desigualdades socioeconómicas.', 2023),
(3, 'literal', 'low', 'La rama del poder encargada de redactar las leyes en Colombia es la:', '["Ejecutiva", "Judicial", "Electoral", "Legislativa"]'::jsonb, 3, 'El Congreso de la República (Rama Legislativa) tiene la función de hacer las leyes.', 2024),
(3, 'general', 'medium', 'La Revolución Industrial provocó a largo plazo un cambio demográfico caracterizado por:', '["El retorno masivo a las áreas rurales.", "El éxodo rural hacia las ciudades en busca de trabajo en fábricas.", "La disminución poblacional mundial por hambrunas.", "La erradicación de las enfermedades infecciosas."]'::jsonb, 1, 'Las fábricas en las ciudades atrajeron a campesinos que abandonaron la agricultura en busca de salario.', 2025),
(3, 'interpretacion', 'high', 'La inflación se entiende comúnmente como:', '["El aumento sostenido y generalizado de los precios de bienes y servicios.", "La bajada de los precios de todo el mercado.", "El aumento de los salarios reales de toda la población.", "La producción excesiva de oro."]'::jsonb, 0, 'Es la pérdida del poder adquisitivo del dinero debido al incremento sostenido de los precios.', 2024),

-- CIENCIAS NATURALES (subject_id = 4)
(4, 'literal', 'medium', '¿Qué organelo celular es el responsable de la respiración celular y la producción de ATP?', '["El núcleo.", "Los lisosomas.", "La mitocondria.", "El aparato de Golgi."]'::jsonb, 2, 'La mitocondria es la "planta de energía" de la célula.', 2025),
(4, 'general', 'high', 'Según la teoría evolutiva de Darwin, la selección natural opera principalmente sobre:', '["Las características adquiridas durante la vida.", "Las variaciones genéticas heredables que otorgan ventaja reproductiva.", "El deseo consciente de los animales por mejorar.", "Las mutaciones inducidas por el clima frío."]'::jsonb, 1, 'La selección natural actúa sobre la variación genética existente en una población que se hereda a la descendencia.', 2024),
(4, 'interpretacion', 'high', 'Si la velocidad de una reacción química se duplica por cada 10°C de aumento, ¿por qué es peligroso para los humanos tener una fiebre superior a 41°C?', '["Porque el sudor se evapora demasiado rápido.", "Porque las enzimas se desnaturalizan y pierden su función, colapsando el metabolismo.", "Porque los glóbulos rojos se congelan.", "Porque se produce demasiada energía."]'::jsonb, 1, 'Las proteínas y enzimas humanas pierden su estructura tridimensional (desnaturalización) a altas temperaturas.', 2025),
(4, 'general', 'medium', 'Un objeto se lanza hacia arriba. En su punto de altura máxima, su velocidad y aceleración son:', '["Velocidad cero, aceleración cero.", "Velocidad cero, aceleración igual a la gravedad (9.8 m/s² hacia abajo).", "Velocidad máxima, aceleración cero.", "Ambas son máximas."]'::jsonb, 1, 'El objeto se detiene un instante (V=0), pero la gravedad sigue actuando sobre él todo el tiempo.', 2023),
(4, 'interpretacion', 'high', 'En una red trófica, si se elimina al depredador ápice (cima de la cadena), generalmente:', '["El ecosistema mejora inmediatamente.", "Las poblaciones de herbívoros se disparan, lo que puede llevar al agotamiento de la vegetación.", "Los descomponedores mueren.", "No ocurre nada importante."]'::jsonb, 1, 'Sin control, las presas se multiplican exponencialmente causando sobrepastoreo.', 2024),
(4, 'literal', 'low', 'El elemento químico más abundante en la atmósfera terrestre es:', '["Oxígeno", "Dióxido de Carbono", "Nitrógeno", "Hidrógeno"]'::jsonb, 2, 'El Nitrógeno constituye aproximadamente el 78% de la atmósfera terrestre.', 2025),
(4, 'general', 'medium', 'La primera ley de la termodinámica establece que:', '["El calor siempre fluye del cuerpo frío al caliente.", "La energía no se crea ni se destruye, solo se transforma.", "La entropía del universo siempre aumenta.", "La masa es igual a la energía."]'::jsonb, 1, 'También conocida como la ley de la conservación de la energía.', 2024),
(4, 'interpretacion', 'high', '¿Por qué el hielo flota en el agua líquida?', '["Porque el hielo tiene una mayor densidad que el agua líquida.", "Porque al congelarse, las moléculas de agua se expanden formando una estructura cristalina menos densa que el líquido.", "Porque el hielo está lleno de burbujas de oxígeno.", "Porque el agua líquida repele los sólidos."]'::jsonb, 1, 'El agua tiene una anomalía de densidad, alcanzando su máxima densidad a los 4°C. Al hacerse hielo, se expande y su densidad disminuye.', 2025),

-- INGLÉS (subject_id = 5)
(5, 'literal', 'low', 'Which is the correct negative form of the present simple sentence "She likes coffee"?', '["She do not likes coffee.", "She not likes coffee.", "She doesn''t like coffee.", "She isn''t like coffee."]'::jsonb, 2, 'Third person singular negative requires "doesn''t" and the verb in base form.', 2024),
(5, 'general', 'medium', 'Choose the correct preposition: "I was born ___ the 15th of March."', '["in", "at", "on", "by"]'::jsonb, 2, '"On" is used for specific days and dates.', 2025),
(5, 'interpretacion', 'high', 'Reading context: "The movie was so predictable; I figured out the ending in the first ten minutes." The word "predictable" means:', '["Very scary.", "Easy to foresee or guess what will happen.", "Expensive to produce.", "Too long."]'::jsonb, 1, 'Predictable means capable of being predicted or anticipated.', 2023),
(5, 'general', 'high', 'Complete the second conditional sentence: "If I ___ a million dollars, I ___ travel the world."', '["have / will", "had / would", "had / will", "have / would"]'::jsonb, 1, 'Second conditional uses past tense in the if-clause and would + base verb in the result clause.', 2024),
(5, 'interpretacion', 'high', 'Phrasal verb: "The manager decided to call off the meeting because of the storm." What does "call off" mean?', '["To postpone.", "To cancel.", "To start early.", "To announce loudly."]'::jsonb, 1, 'The phrasal verb "call off" means to cancel an event.', 2025),
(5, 'literal', 'medium', 'What is the past participle of the verb "To break"?', '["Breaked", "Broke", "Broken", "Braking"]'::jsonb, 2, 'Break - Broke - Broken.', 2024),
(5, 'general', 'medium', 'Choose the correct sentence:', '["I have been to London last year.", "I went to London last year.", "I go to London last year.", "I was going to London since last year."]'::jsonb, 1, '"Last year" is a specific time in the past, so we use the simple past tense.', 2025),
(5, 'interpretacion', 'high', 'If someone says "It''s raining cats and dogs", they mean:', '["Animals are falling from the sky.", "It is raining very heavily.", "It is a sunny day.", "There are many pets in the street."]'::jsonb, 1, 'This is a common English idiom for heavy rain.', 2024);
